[phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.openssl", "php82Extensions.json"]

[phases.install]
cmds = ["echo 'PHP installation completed'"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "php -S 0.0.0.0:$PORT" 